#ifndef YB_ViewBasis_H
#define YB_ViewBasis_H

#include <iostream>
#include <map>
#include <vector>
#include "YB_ViewMessage.h"
#include "YB_DataBasis.h"
#include <functional>
#include "YB_DataSource_Interface.h"
//#include "YB_ViewItemBasis.h"				// Forward declaration - some c++ specific trap

using namespace std;
using namespace YBPersistence;

namespace YBConsoleViews
{
	class YB_ViewItemBasis;					// Forward declaration - some c++ specific trap

	class YB_ViewBasis : public YBPersistence::YB_DataBasis
	{
	public:
		YB_ViewBasis();
		YB_ViewBasis(int* width, int* height);
		~YB_ViewBasis();
		#pragma region Copy assignment operator
		//=====================================================================================================================
		//Suggestion given by chatGPT to solve C2280 and deleted function error:
		// it's possible that the error is related to the copy assignment operator of your YB_User class. If the YB_User 
		// class contains non-trivial member variables (like pointers or dynamically allocated resources), the default 
		// copy assignment operator generated by the compiler might not handle them correctly.
		// To resolve this, you should define a copy assignment operator for your YB_User class that performs a deep copy
		// of its members.
		YB_ViewBasis& operator=(const YB_ViewBasis& other) {
			if (this != &other) {
				Title = other.Title;
				ViewType = other.ViewType;
				w = other.w;
				h = other.h;
				Source = other.Source;
				GotoView = other.GotoView;
				subItemsList = other.subItemsList;
				viewArray = other.viewArray;
				dataSource = other.dataSource;


				// Deep copy of other resources, if any
				// For example, if 'myfile' is a pointer, you might need to handle it here

				// Call parent class copy assignment operator
				YB_DataBasis::operator=(other);
			}
			return *this;
		}
		//Also see to the explanation:
		// https://stackoverflow.com/questions/31264984/c-compiler-error-c2280-attempting-to-reference-a-deleted-function-in-visual
		//YB_ViewBasis& operator=(const YB_ViewBasis&) = default;		//this passed syntax check but doesn't solve the C2280
		//
		//The best solution will be try using pointers as much as possible instead of copying value, e.g.:
		//change the dataSet to map<int, TData*> in the persistor class;
		//However I will not go through this direction for simplicity consideration.
		//=====================================================================================================================
		#pragma endregion

		string							ViewType = "";
		string							Title = "";
		int								w = 200, h = 32;									//view size
		char							Background = '.';
		string							Source="";
		string							GotoView="";
		vector<YB_ViewItemBasis*>		subItemsList;

		//void AddViewItem(YB_ViewItemBasis item);
		//void AddViewItems(vector<YB_ViewItemBasis> items);

		virtual string*					Serialize()											override;
		virtual void					Serialize(std::stringstream& strStream)				override;
		void							Deserialize(string line);
		virtual void					Deserialize(string line, const char* separator)		override;
		//void Serialize(ofstream* output) override;

		void							Init();												
		virtual	string*					Bind(string* bindName);								//datasource VM -> view: Bind a value to a viewItem.
		virtual void					BindValues();										//datasource VM -> view: Bind values to viewItems from dataSource.
		virtual void					ReverseBind();										//view -> datasource VM: Reverse binding to VM (and upate/save)
		virtual void					OnKey(int* keycode);
		virtual void					OnChildReturn(YB_ViewMessageBasis msg);
		virtual vector<char*>			Render();
		void							Init_Background(char background);
		void							Fill_Background(char background);
		void							Clear_Background();

		std::function<void()>			ViewReturnCallback;
	protected:
		vector<YB_ViewItemBasis*>		focusableItems;					//Todo: move this code to basis or Init()

	private:
		bool							isUpdated = true;
		YB_DataSource_Interface*					dataSource;
		vector<char*>					viewArray;
		int								currentItemIndex = -1;
	};
}
#endif //YB_ViewBasis_H
